---
title: "hw_lubridate_purrr"
author: "Jack Kuo Chang"
date: "2025-02-21"
output: html_document
---

```{r, message = FALSE}
library(lubridate)
library(purrr)
library(tidyverse)
```

```{r}
#1Generate a sequence of dates from January 1, 2015 to December 31, 2025, spaced by
#every two months. Extract the year, quarter, and ISO week #number for each date.

dates_seq <- seq(ymd("2015-01-01"), ymd("2025-12-31"), by = "2 months")
year_values <- year(dates_seq)
quarter_values <- quarter(dates_seq)
iso_week_values <- isoweek(dates_seq)

result_ex1 <- data.frame(Date = dates_seq, Year = year_values, Quarter = quarter_values, ISO_Week = iso_week_values)
print(result_ex1)
```

```{r}
#Question 2:
#Given the following dates, compute the difference in months and weeks between each #consecutive pair.
#sample_dates <- c("2018-03-15", "2020-07-20", "2023-01-10", "2025-09-05")


sample_dates <- ymd(c("2018-03-15", "2020-07-20", "2023-01-10", "2025-09-05"))

month_diffs <- diff(sample_dates) / dmonths(1)  
week_diffs <- diff(sample_dates) / dweeks(1) 

result_ex2 <- data.frame(
  Start_Date = sample_dates[-length(sample_dates)],
  End_Date = sample_dates[-1],
  Month_Difference = month_diffs,
  Week_Difference = week_diffs
)
print(result_ex2)
```
```{r}
#Question 3:
#Using map() and map_dbl(), compute the mean, median, and standard deviation for each
#numeric vector in the following list:
#num_lists <- list(c(4, 16, 25, 36, 49), c(2.3, 5.7, 8.1, 11.4), c(10, 20, 30, 40, 50))


num_lists <- list(c(4, 16, 25, 36, 49), c(2.3, 5.7, 8.1, 11.4), c(10, 20, 30, 40, 50))

stats <- tibble(
  mean = map_dbl(num_lists, mean),
  median = map_dbl(num_lists, median),
  sd = map_dbl(num_lists, sd)
)

print(stats)
```
```{r}

#Question 4:
#Given a list of mixed date formats, use map() and possibly() from purrr to safely convert
#them to Date format and extract the month name.
#date_strings <- list("2023-06-10", "2022/12/25", "15-Aug-2021", "InvalidDate")

date_strings <- list("2023-06-10", "2022/12/25", "15-Aug-2021", "InvalidDate")

extract_month <- function(date_str) {
  
 d <- parse_date_time(date_str, orders =c("ymd", "dmy"))

 if(is.na(d)) {
  stop("Date conversion failed")
 }
 month(d, label = TRUE, abbr = FALSE) %>% as.character()
}

safe_extract_month <- possibly(extract_month, otherwise = NA_character_)

month_names <- map(date_strings, safe_extract_month)

print(month_names)

```

